# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://jcrosasb.github.io/deck_of_cards_2/"

git_url = "https://github.com/jcrosasb/deck_of_cards_2/tree/master/"

def custom_doc_links(name): return None
